/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddNewNewspaperDialog.java
 *
 * Created on Apr 13, 2012, 8:58:02 PM
 */
package pressdocumentation.gui;

import pressdocumentation.pojos.Newspaper;
import org.jdesktop.application.Action;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import pressdocumentation.ArticleHandler;
import pressdocumentation.ArticleListener;
import pressdocumentation.PrefsHandler;
import pressdocumentation.pojos.Article;

/**
 *
 * @author ETHGGY
 */
public class AddNewNewspaperDialog extends javax.swing.JDialog {
// check
//    private PressDocumentationView pdv;
    /** Creates new form AddNewNewspaperDialog */
    public AddNewNewspaperDialog(DialogServices parent, boolean modal) {
        super(parent.getFrame(), modal);
        
//        pdv = parent;
        initComponents();
        
        PrefsHandler ph = PrefsHandler.getInstance();
        

        String[] media = ph.getDefaults("media");

        jComboBox1.removeAllItems();
        for (int i = 0; i < media.length; i++) {
            String string = media[i];

            jComboBox1.addItem(string);

        }

        String[] type = ph.getDefaults("type");

        jComboBox2.removeAllItems();
        for (int i = 0; i < type.length; i++) {
            String string = type[i];

            jComboBox2.addItem(string);

        }

            

        
    }
/*
private void createDefaults(Document doc) {
    Element press = doc.createElement("defaults");

    Element nameElement = doc.createElement("media");
    nameElement.appendChild(doc.createTextNode("ingatlan"));
    press.appendChild(nameElement);        
    nameElement = doc.createElement("media");
    nameElement.appendChild(doc.createTextNode("gazd/közélet"));
    press.appendChild(nameElement);        

    nameElement = doc.createElement("type");
    nameElement.appendChild(doc.createTextNode("online"));
    press.appendChild(nameElement);        
    nameElement = doc.createElement("type");
    nameElement.appendChild(doc.createTextNode("offline"));
    press.appendChild(nameElement);        
    nameElement = doc.createElement("type");
    nameElement.appendChild(doc.createTextNode("elektronikus"));
    press.appendChild(nameElement);        

    doc.appendChild(press);
     // write the content into xml file
    TransformerFactory transformerFactory = TransformerFactory.newInstance();
    Transformer transformer;
    try {
        transformer = transformerFactory.newTransformer();
        transformer.setOutputProperty(OutputKeys.INDENT, "yes"); 
        DOMSource source = new DOMSource(doc);
        StreamResult result = new StreamResult(new File("pressdocumentation.xml"));
        transformer.transform(source, result);

    } catch (TransformerConfigurationException ex) {
        Logger.getLogger(AddNewNewspaperDialog.class.getName()).log(Level.SEVERE, null, ex);
    } catch (TransformerException ex) {
        Logger.getLogger(AddNewNewspaperDialog.class.getName()).log(Level.SEVERE, null, ex);
    }

}    
  */  
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pressdocumentation.PressDocumentationApp.class).getContext().getResourceMap(AddNewNewspaperDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ingatlan", "gazd/közélet" }));
        jComboBox1.setName("jComboBox1"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "online", "offline", "elektronikus" }));
        jComboBox2.setName("jComboBox2"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(pressdocumentation.PressDocumentationApp.class).getContext().getActionMap(AddNewNewspaperDialog.class, this);
        jButton1.setAction(actionMap.get("cancel")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setAction(actionMap.get("ok")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    @Action
    public void cancel() {
        this.setVisible(false);
        
    }

    @Action
    public void ok() {
//        try {
            this.setVisible(false);
            
            
//            URL url =  new URL(newspaper.getLink());
//            newspaper.setLink(url.getHost());
            
//        } catch (MalformedURLException ex) {
//            Logger.getLogger(AddNewNewspaperDialog.class.getName()).log(Level.SEVERE, null, ex);
//        }

//        pdv.addNewsPaper(getArticle());
  
            ArticleHandler ah = ArticleHandler.createInstance();
            
            ah.notifyListeners(ArticleListener.NEWSPAPER_MODIFIED, getArticle());
            
        
    }

    private Article article;
    private Newspaper newspaper;

    public Article getArticle() {
        article.setPaper(getNewspaper());
        
        return article;
    }

    public void setArticle(Article article) {
        this.article = article;
        setNewspaper(article.getPaper());
    }

    
    
    
    private Newspaper getNewspaper() {
        newspaper.setName(jTextField1.getText());
        newspaper.setMedia(jComboBox1.getSelectedItem().toString());
        newspaper.setType(jComboBox2.getSelectedItem().toString());
        return newspaper;
    }

    private void setNewspaper(Newspaper newspaper) {
        this.newspaper = newspaper;
        jTextField2.setText(newspaper.getLink());
  
        
        
        
    }
            
    private static String[] getTagValueList(String sTag, Element eElement) {
        NodeList nlList = eElement.getElementsByTagName(sTag);

        String[] sa = new String[nlList.getLength()];
        
        for (int i = 0; i < nlList.getLength(); i++) {
            Node nValue = (Node) nlList.item(i);
            
            sa[i] = nValue.getNodeValue();
            
        }
        
        return sa;
    }    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
